sudo: required
services:
    - docker

before_install:
    - docker build -t subham39/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true subham39/react-test npm test -- --coverage

after_sucess:
    -docker build -t subham39/multi-client ./client
    -docker build -t subham39/multi-nginx ./nginx
    -docker build -t subham39/multi-server ./server
    -docker build -t subham39/multi-worker ./worker
    # login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push subham39/multi-client
    - docker push subham39/multi-nginx
    - docker push subham39/multi-server
    - docker push subham39/multi-worker

    
    