sudo: required
services:
    - docker

before_install:
    - docker duild -t subham39/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true subham39/react-test npm test -- --coverage

after_sucess:
    -docker build -t subham39/multi-client ./client
    -docker build -t subham39/multi-nginx ./nginx
    -docker build -t subham39/multi-server ./server
    -docker build -t subham39/multi-worker ./worker
    # login to docker cli
    

    
    